description: "My eval"

providers:
 - "ollama:chat:llama3.2"

prompts:
  - file://./prompts.json
  
# Set up the conversation history
defaultTest:
  vars:
    system_message: Answer concisely
    messages:
      - user: Who founded Facebook?
      - assistant: Mark Zuckerberg

# Test multiple follow-ups
tests:
  - file://./followup.csv