raw_data_path: ../data/raw_data/
temp_bins:
  low: {min: 0.0, max: 0.4, num_points: 12}
  medium: {min: 0.4, max: 0.8, num_points: 24}
  high: {min: 0.8, max: 1.2, num_points: 48}
split_ratio: 5  # 5:1 train:test
hold_out_fraction: 0.2  # 20% models held out
held_out_models: [google_gemma-12b-it, meta-llama_Llama-3.2-1B,
                  meta-llama_Meta-Llama-3-70B-Instruct, microsoft_Phi-4-multimodal-instruct,
                  mistralai_Devstral-Small-2505, Qwen_QwQ-32B]
random_seed: 42